### ISSUE TITLE
Crash when launching book from list

### ISSUE THREAD

**Issue by bryanrezende** [GianniCarlo/Audiobook-Player#24] opened 2017-11-06 19:43 UTC
Seems like there's a bug in the latest app store version. When you try to add a new book and play it, the app immediately crashes. Tested on iOS 11 on iPhone 6s Plus and iPhone X. Can't take a look at what's causing it right now, but I'll see what I can find after work!

**Comment by GianniCarlo** [comment] 2017-11-06 20:33
Thanks for letting me know bryan, I'll look into it asap

**Comment by GianniCarlo** [comment] 2017-11-06 20:40
I took it out of the appstore, it looks like an OOM problem, when I run it from Xcode it launches the player with no problem, but it sort of "jumps" the first time 🤔, I'll try to solve it

**Comment by bryanrezende** [comment] 2017-11-06 20:43
Interesting. Let me know if there's anything I can do to help! I should be able to start taking a look in a few hours.

**Comment by GianniCarlo** [comment] 2017-11-07 02:08
When running Xcode with the scheme set with the build configuration to `Release` I can reproduce the crash. But it randomly crashes on either:

`NotificationCenter.default.addObserver(self, selector: #selector(self.requestReview), name: Notification.Name.AudiobookPlayer.requestReview, object: nil)`

or

`self.sliderView.addTarget(self, action: #selector(self.sliderChanged(_:)), for: .valueChanged)`

it's a `EXC_BAD_ACCESS` crash, sometimes it crashes at other points, but it never reaches the load book part so it can't be due to OOM. 

Have you found out something @bryanrezende on your end? I'm grasping at straws, I'll try running Instruments to see if there are any memory leaks 🤔

**Comment by GianniCarlo** [comment] 2017-11-07 02:11
I tested without the `DeckTransition` presentation to rule out that, but the problem persists

**Comment by GianniCarlo** [comment] 2017-11-07 03:08
Ok, so it solved itself if I disable swift optimization for release build 🤔, I'll send a new release to the appstore without any optimization. This sure is unusual

**Comment by bryanrezende** [comment] 2017-11-07 03:12
Sorry, I only just now got home! I had something come up and was away from my computer. That is really strange... have you had the swift optimization enabled for all previous builds? I don't think we changed anything that would interfere with that, unless one of the dependencies changed something? We could try some older commits and see if they build properly.

**Comment by GianniCarlo** [comment] 2017-11-07 03:16
I haven't tinkered with that setting before, so for debug they are disabled by default and for release they are set to "fast". The only new dependency I added recently is `DeckTransition` 🤔 we could try running it in release mode with optimizations and without that dependency to see if that's it.

I got the idea to check the swift optimization from here: https://stackoverflow.com/questions/25629841/app-crashes-in-release-build-but-not-in-debug

**Comment by GianniCarlo** [comment] 2017-11-07 03:17
For now I'll send a new release without any compiler optimizations to the appstore to have it running again, I'll look into requesting an expedited review

**Comment by bryanrezende** [comment] 2017-11-07 03:21
Sounds like a plan. Apple's been getting much better about the speed of their reviews, but I've always had issues with getting expedited reviews. Fingers crossed they run it through quickly! 

Out of curiosity, have you done most of your testing on device on in sim? I'm trying out debug mode with optimization but want to make sure I'm hitting what was failing before.

**Comment by bryanrezende** [comment] 2017-11-07 03:50
I'm not sure what caused it yet, but it seems like the issue first appears when my player ux update got merged in at [this commit](https://github.com/GianniCarlo/Audiobook-Player/commit/cd937be09fc8040d0f4c7a15877f9d120eb95103). It's got to be something about how I modified the player. I wonder if the changes I made to the storyboard could have affected anything? Possibly how I'm accessing the image container? I've never used the swift optimization before so I'm trying to learn as much as I can!

**Comment by GianniCarlo** [comment] 2017-11-07 12:35
I usually test it on my device (iPhone 6s). 🤔 that's a possibility I guess, but even so, there are no dangling iboutlets and on debug runs fine so it shouldn't be a problem. We could try recreating that viewcontroller in particular, but I think we could focus our energy better given that on Release it works fine w/o compiler compatibility. Let's give it time and wait for the next minor Xcode/Swift version and see if it sorts itself out.

For now I'll leave this issue open to remember to test out enabling compiler optimization for the next Xcode version.

**Comment by GianniCarlo** [comment] 2017-11-07 19:26
I tested it from the Appstore and it's ok 👌

**Comment by bryanrezende** [comment] 2017-11-07 20:14
Awesome!! Great job finding that issue and getting it fixed so quickly. I wouldn't even have thought to check the swift optimizer.

**Comment by GianniCarlo** [comment] 2017-11-09 14:50
Closing in favor of #25

**Closed by GianniCarlo** 2017-11-09 14:50 UTC
